### PR TITLE
try to fix saga

### LINKED ISSUE #389: SAGA flow direction to GRIB tool: file extension not working anymore
In QGIS 3.6.0 it worked well to save the SAGA flow direction output to grib format by renaming the extension in the dialogue of the tool (https://youtu.be/qN_UC0AZhVM). This doesn't work anymore in 3.6.2, probably because of checking of accepted GDAL extensions. It would be better that the tool forces to give the .grb extension.

### LINKED ISSUE #428: SAGA conversion algorithm creates two files
One is a xxx.grb and another is xxx.grb.tiff 

They are both with identical size.

### LINKED ISSUE #430: Problem creating grib from SAGA flow direction result
https://lists.osgeo.org/pipermail/qgis-user/2020-April/045340.html

image (13)

### PR DESCRIPTION
**Pull request by PeterPetrik**
fix #430
fix #389

@saberraz can you please test

### CODE REVIEW

**Comment by PeterPetrik** [comment]
@jvdkwast Hi, could you please test the SAGA processing alg?

**Comment by jvdkwast** [comment]
I tried with SAGA flow direction output in EPSG:32632 (Rur catchment dataset).
I got the following error in the log:
image
But it generates the GRIB and the GRIB works correctly.

I tried with SAGA flow direction output in EPSG:28992 (data from #430)
It shows the following error:
image
And doesn't generate the GRIB file

This is in QGIS 3.16.3.
In 3.10.4 the plugin doesn't install, probably not supported.

**Comment by PeterPetrik** [comment]
Thanks, submitted the fix for the first one, the second issue is expected (problem with gdal and proj - not related to crayfish processing alg, we at least show the correct error to user... maybe you need to first reproject and try again?)

**Comment by jvdkwast** [comment]
After reprojection from EPSG:28992 to EPSG:32631 in works. Indeed gdal/proj issue.

**Comment by PeterPetrik** [comment]
@jvdkwast thanks for testing! I will release today (to be used in 3.17+ so master only). If there are any issues, just drop me a mail...

**Pull request merged**
