### PR TITLE
animation: optionally keep intermediate images

### PR DESCRIPTION
**Pull request by michelk**

### CODE REVIEW

**Comment by michelk** [comment]
This addresses #112.

**Comment by saberraz** [comment]
@michelk could you address the error in the travis so that we can review and merge it to master?

**Comment by PeterPetrik** [comment]
Screenshot 2019-09-16 at 08 24 38
@saberraz

**Comment by PeterPetrik** [comment]
@michelk thank you for your contribution and sorry for such a long delay for merging.. it somehow slipped through my mail box unrecognized. good work!

**Comment by michelk** [comment]
Thanks, Peter.

**Pull request merged**
